In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sehaj1104/indian-road-accident-dataset-20222025")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).
Path to dataset files: C:\Users\raiti\.cache\kagglehub\datasets\sehaj1104\indian-road-accident-dataset-20222025\versions\1

In [3]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [4]:
data = pd.read_csv('C:\\Users\\raiti\\.cache\\kagglehub\\datasets\\sehaj1104\\indian-road-accident-dataset-20222025\\versions\\1\\indian_roads_dataset.csv')
data.sample(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
9405,9405,Hyderabad,Telangana,17.342746,78.443359,2022-05-03,0:00,0,Tuesday,0,...,medium,37,low,drunk driving,minor,3,0,0,NaN,0.25
12353,12353,Chennai,Tamil Nadu,13.100182,80.284169,2022-08-29,13:00,13,Monday,0,...,high,40,high,overspeeding,minor,2,0,0,NaN,0.30
11416,11416,Mumbai,Maharashtra,19.066758,72.744687,2024-07-25,6:00,6,Thursday,0,...,medium,17,medium,distraction,minor,4,3,0,NaN,0.25
12604,12604,Delhi,Delhi,28.617555,77.172533,2023-12-11,8:00,8,Monday,0,...,low,30,medium,weather,fatal,1,1,1,NaN,0.80
11669,11669,Bangalore,Karnataka,12.931612,77.570960,2023-08-14,19:00,19,Monday,0,...,low,22,medium,poor road,minor,4,0,1,NaN,0.60

In [5]:
data.shape

(20000, 24)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB

In [7]:
data.describe()

,accident_id,latitude,longitude,hour,is_weekend,lanes,traffic_signal,temperature,vehicles_involved,casualties,is_peak_hour,risk_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,9999.500000,20.389207,78.173330,11.487200,0.286150,3.493950,0.499850,27.579600,2.992000,1.726450,0.247400,0.437585
std,5773.647028,6.165791,4.485967,6.945563,0.451972,1.705406,0.500012,7.454746,1.415534,1.489104,0.431512,0.218130
min,0.000000,12.800172,72.700017,0.000000,0.000000,1.000000,0.000000,15.000000,1.000000,0.000000,0.000000,0.100000
25%,4999.750000,13.198653,73.997979,5.000000,0.000000,2.000000,0.000000,21.000000,2.000000,1.000000,0.000000,0.250000
50%,9999.500000,18.812008,77.297000,12.000000,0.000000,4.000000,0.000000,28.000000,3.000000,1.000000,0.000000,0.450000
75%,14999.250000,28.402467,80.111089,18.000000,1.000000,5.000000,1.000000,34.000000,4.000000,3.000000,0.000000,0.600000
max,19999.000000,30.799960,88.499861,23.000000,1.000000,6.000000,1.000000,40.000000,5.000000,5.000000,1.000000,1.000000

In [8]:
data['festival'].fillna("None", inplace=True)

C:\Users\raiti\AppData\Local\Temp\ipykernel_13316\4191669523.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['festival'].fillna("None", inplace=True)

In [9]:
data['festival'].isnull().sum()

0

In [10]:
data['is_festival'] = np.where(data['festival'] == "None", 0, 1)

In [11]:
data['is_festival'].value_counts()

is_festival
0    19885
1      115
Name: count, dtype: int64

In [12]:
data['date'] = pd.to_datetime(data['date'])
# data['time'] = pd.to_datetime(data['time']).dt.time

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  datetime64[ns]
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           20000 non-null  object
 23  risk_score         20000 non-null  float64
 24  is_festival        20000 non-null  int32
dtypes: datetime64[ns](1), float64(3), int32(1), int64(9), object(11)
memory usage: 3.7+ MB

In [14]:
print(data['time'].iloc[0])
# print(type(data['time'].iloc[0]))

5:00

In [15]:
data['month'] = data['date'].dt.month
data['year'] = data['date'].dt.year

In [16]:
df = data.drop(columns=['time', 'is_weekend', 'date'])

In [17]:
df

,accident_id,city,state,latitude,longitude,hour,day_of_week,road_type,lanes,traffic_signal,...,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,is_festival,month,year
0,0,Pune,Maharashtra,18.680827,73.930388,5,Sunday,highway,3,1,...,weather,fatal,2,2,0,None,0.85,0,10,2023
1,1,Mumbai,Maharashtra,18.817732,72.790846,4,Sunday,urban,4,0,...,weather,major,4,3,0,None,0.10,0,5,2023
2,2,Mumbai,Maharashtra,19.096889,72.819424,13,Wednesday,urban,3,0,...,weather,minor,1,1,0,None,0.45,0,7,2024
3,3,Chandigarh,Punjab,30.787805,76.847507,11,Sunday,urban,1,1,...,distraction,minor,5,2,0,None,0.65,0,3,2025
4,4,Chennai,Tamil Nadu,12.965155,80.283313,16,Thursday,highway,3,1,...,distraction,minor,2,1,0,None,0.10,0,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,Bangalore,Karnataka,13.092276,77.599571,3,Thursday,urban,1,1,...,distraction,minor,3,2,0,None,0.10,0,9,2022
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,1,Saturday,urban,1,1,...,distraction,major,4,2,0,None,0.10,0,11,2023
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,15,Saturday,rural,3,0,...,weather,minor,3,3,0,None,0.10,0,6,2022
19998,19998,Kolkata,West Bengal,22.454882,88.322213,4,Sunday,highway,3,1,...,poor road,minor,1,0,0,None,0.10,0,3,2023
19999,19999,Delhi,Delhi,28.510266,77.065301,23,Friday,highway,1,1,...,overspeeding,minor,4,2,0,None,0.65,0,7,2024

In [18]:
df['weather'].value_counts()

weather
clear    6690
rain     6677
fog      6633
Name: count, dtype: int64